name: himlayang_nav
description: Himlayang Pilipino Navigation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  zxcvbn: ^1.0.0
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
  crypto: ^3.0.1
  convert: ^3.0.1
  otp: ^3.1.2
  qr_flutter: ^4.1.0
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.9
  location: ^4.0.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.0.9
  permission_handler: ^10.2.0
  fl_chart: ^0.62.0
  flutter_map: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/himlogo2.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/images/himlogo2.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "lib/images/himlogo2.png"
    icon_size: 48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - .env

flutter_native_splash:
  image: lib/images/himlogo.png
  color: "9A9A9A"
